### PR TITLE
Remove 'famous' namespace

### PR DESCRIPTION
**Pull request by jd-carroll**
Removes the namespace prefix on all modules.

Fix for #7

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
This fix is unfortunately not correct... I would still like to explore what is going on but the ```famous``` name space is definitely necessary for the require.js build.  Otherwise everything gets put in a src namespace, and require famous/*/* will never work

**Comment by jd-carroll** [comment]
You might be right, let me look at this tonight..

If everything is put into a `src` namespace then the issue is with the [paths config](https://github.com/FamousTools/famous-dist-generator/blob/master/lib/index.js#L332) option.  I did not validate the output when I was testing this weekend and will do so tonight.

Might have to do something like:

```
paths = {
    'famous': '../famous'
}
```

**Comment by jd-carroll** [comment]
I was able to play around with the `paths` and `map` configuration elements last night (along with a couple of others) and couldn't put together anything meaningful.

I think the answer is going to be copying the contents of `src` dir (the desired elements) into a separate `famous` dir and doing the build from there.  That way requirejs is able to process the dir normally and everything will be under the 'famous' module name.

We will just need to be mindful of the git repository, and know that by copying the files we run the risk of committing build artifacts.

**Comment by TheAlphaNerd** [comment]
This is going to be overly complicated, and it just rubs me the wrong way.

To be quite honest I think that the dist generator as a entity needs a big ole rewrite.

**Comment by jd-carroll** [comment]
Wouldn't disagree with any of that..

Shoot me an email some time and we can schedule a call to outline things.  

(Just update my profile)

**Comment by TheAlphaNerd** [comment]
closing as this PR doesn't make sense with the new version

**Pull request closed without merging**
