### PR TITLE
upgrade derequire, it's like 60 times faster

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
AMAZING! I'm just about to get on a flight, but I'll get to this in the air if I have wifi!

**Comment by calvinmetcalf** [comment]
it switches from esprima to acorn so in theory there could be some code that parsed before that it can't now so just beware

**Comment by TheAlphaNerd** [comment]
There are a ton of tests, so if there is any weirdness they will break.  It is odd that travis didn't get run on this though.

**Comment by TheAlphaNerd** [comment]
Done did it :smile:

**Pull request merged**
